### ISSUE TITLE
[BUG]  Picture quality bug

### ISSUE THREAD

**Issue by 1425115471** [LoneDev6/Issues-ItemsAdder#305] opened 2020-06-19 02:52 UTC
After using the plug-in, bug appears in the picture quality
Small spots will appear after use

1.This is not used
![D7BC W_1AI8_($}Z}CDITK8](https://user-images.githubusercontent.com/29402452/85091957-4170e400-b21b-11ea-86b7-03f6b6503b76.png)

2.This is after use
![P2 Q})S 3BJ{RDAGAQ~8CBV](https://user-images.githubusercontent.com/29402452/85091986-4d5ca600-b21b-11ea-8246-28d96ee22490.png)

 - Server version: (example: paper 1.15.2)
 - Client version: (example: fabric 1.15.2)

**Comment by LoneDev6** [comment] 2020-06-24 09:30
Can you check if you can increase the mipmap level in video settings?

**Comment by LoneDev6** [comment] 2020-06-24 09:51
Should be fixed in next update:

- fixed mipmap bug caused by non power of 2 textures (icon_refresh, four_leaf_clover), you have to use /iazip again to fix this and reupload to dropbox https://github.com/LoneDev6/Issues-ItemsAdder/issues/305

**Closed by LoneDev6** 2020-06-24 09:51 UTC
Labels: bug
